config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions do
    resources :answers
  end
  resources :users do
    post :follow, on: :member
  end
  resources :topics do
    post :follow, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :answers
  validates :question, uniqueness: true, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions
  has_many :users, through: :topic_follwers
  has_many :topic_follwers
  validates :topic, uniqueness: true, presence: true
end

app/models/topic_follower.rb
class TopicFollower < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  validates :topic, uniqueness: { scope: :user, message: 'Already following' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :answers
  has_many :user_followers
  has_many :topic_followers
  has_many :following, through: :user_followers, source: :follower
  has_many :topics, through: :topic_followers
end

app/models/user_follower.rb
class UserFollower < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'
  validates :user, uniqueness: { scope: :follower, message: 'Already following' }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params.merge(user: current_user))
    redirect_to question_path(@question), alert: @answer.errors.full_messages.join(',') and return unless @answer.save

    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  rescue_from ActionController::RoutingError, with: :render_root

  private

  def render_root
    redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @topics = Topic.all
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = current_user.questions.build(question_params)
    render 'new' and return unless @question.save

    redirect_to root_path, alert: @question.errors.full_messages.join(',')
  end

  private

  def question_params
    params.require(:question).permit(:question, :topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    render 'new' and return unless @topic.save

    redirect_to questions_path, notice: 'Topic created'
  end

  def follow
    follower = current_user.topic_followers.build(topic_id: params[:id])
    redirect_to root_path, alert: follower.errors.full_messages.join(',') and return unless follower.save

    redirect_to root_path, notice: 'Followed successfully'
  end

  private

  def topic_params
    params.require(:topic).permit(:topic)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def follow
    follower = current_user.user_followers.build(follower_id: params[:id])
    redirect_to root_path, alert: follower.errors.full_messages.join(',') and return unless follower.save

    redirect_to root_path, notice: 'Followed successfully'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PrakashTask
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice
      = notice
    %p.alert
      = alert
    - if current_user.present?
      = link_to 'Back', :back
      = link_to "logout", destroy_user_session_path, method: :delete
      = link_to "New topic", new_topic_path

    %br
    = yield

app/views/questions/index.html.haml
%h2 Questions
-@questions.each do |question|
	= link_to "Question-  #{question.question}", question, class: "question"
	%br
%br
= link_to 'New Question', new_question_path

%h2 Topics
- @topics.each do |topic|
	Follow this topic: 
	= link_to topic.topic, follow_topic_path(topic), method: :post, class: "follow_topic"
	%br

app/views/questions/new.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :question
    = f.text_field :question
  %br/
  .field
    = f.label :topic
    = f.select :topic_id, Topic.all.map{ |topic| [topic.topic, topic.id]}

  .actions
    = f.submit 'Save'

app/views/questions/show.html.haml
Follow this topic: 
= link_to "#{@question.topic.topic}", follow_topic_path(@question.topic), method: :post, class: "follow_topic"
%br
Follow this User: 
= link_to @question.user.email, follow_user_path(@question.user), method: :post, class: "follow_user"

%h2 Answers
- @question.answers.each do |answer|
  %p.answer
    answer: 
    = answer.answer
%br

%h3 Submit your answer
= form_for :answer, url: question_answers_path(@question.id) do |form|
  .field
    = form.label :answer
    = form.text_field :answer
  .actions
    = form.submit 'Save'

app/views/topics/new.html.haml
%h1 New topic

= link_to 'Back', root_path

= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :topic
    = f.text_field :topic
  .actions
    = f.submit 'Save'